language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_deploy:
  - echo $(git describe --abbrev=0 --tags)
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run release; fi
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true
