language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_deploy:
  - echo "before $(git describe --abbrev=0 --tags)"
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run release; env TRAVIS_TAG=$(git describe --abbrev=0 --tags); fi
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  name: testing release name
  body: test release body
  on:
    tags: true
