language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
before_script:
  - npm prune
script:
  - echo "before $(git describe --abbrev=0 --tags)"
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run release; env TRAVIS_TAG=$(git describe --abbrev=0 --tags); fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    tags: true
