language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: script
  script:  npm run release
  skip_cleanup: true
  on:
    branch: master
